name: Build the Project

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # setup
    - name: Checkout project sources
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Setup Android NDK
      uses: android-actions/setup-android@v3
    - name: Install NDK and CMake
      run: |
        sdkmanager "ndk;28.2.13676358"
        sdkmanager "cmake;3.22.1"

    # validate and build
    - name: Generate Documents
      run: ./gradlew generateDocs
    - name: Validate Dictionaries
      run: ./gradlew validateLanguages
    - name: Build Languages
      run: ./gradlew buildDefinition buildDictionaryDownloads
    - name: Copy Downloads
      run: ./gradlew copyDownloadsToAssets
    - name: Lint
      run: ./gradlew lint # this actually runs mergeResources, so it must come after the dictionary tasks
    - name: Build 'Lite' and 'Full' APK variants
      run: ./gradlew assembleLiteRelease assembleFullRelease
